export { default as Home } from './Home'
export { default as Exercise } from './Exercise'
export { default as ExerciseDetail } from './ExerciseDetail'
export { default as Tracker } from './Tracker'
export { default as Register } from './Register'
export { default as Login } from './Login'