export { default as Home } from './Home'
export { default as Exercise } from './Exercise'
export { default as Tracker } from './Tracker'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Stats } from './Stats'
export { default as DetailedExercise } from './DetailedExercise'