export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as HorizontalScrollbar } from './HorizontalScrollbar'
export { default as Exercises } from './Exercises'
export { default as ExerciseSearch } from './ExerciseSearch'
export { default as Detail } from './Detail'
export { default as SimilarExercises } from './SimilarExercises'
export { default as ExerciseVideos } from './ExerciseVideos'